<section class="main_content">
    <section class="content_detail">
        <section class="sec_content fl">
            <header>
                <?php echo $categoryInfo['title']; ?> |
                <span class="date_time">
                    <?php
                    $publicTime = new DateTime($article['public_time']);
                    echo date_format($publicTime, 'g:i A');
                    ?> Ngày <?php echo date_format($publicTime, 'd/m/Y'); ?>
                </span>
            </header>
            <div class="news_item">
            <?php echo $article['detail']; ?>
            </div>
        </section>     
        <section class="sec_content fl">
            <header>
                Bài viết khác
            </header>
            <?php foreach ($articles as $item) { ?>    
                    <?php if ($item['id'] != $article['id']) { ?>
                    <li class="other_news"><a href="/<?php echo $item['url_key']; ?>"><?php echo $item['title']; ?></a></li>
                    <?php } ?>
<?php } ?>
        </section>
    </section>
</section>    
