<div class="left_panel fl">
    <div class="left_block">
        <div class="title_box">
            <div class="left_box_title fl"></div>
            <div class="title_box_text">
                Liên kết website
            </div>                            
        </div>
        <div class="left_box_list">
            <ul>
            <?php foreach ($links as $item) { ?>
                <li><a href="<?php echo $item['link']; ?>" target="_blank"><?php echo $item['title']; ?></a></li>
            <?php } ?>                        
            </ul>
        </div>                        
    </div><!-- left_block -->    
    <?php // $this->block("utility") ?>
    <div class="left_block">
        <iframe frameborder="0" marginwidth="0" marginheight="0" src="/lib/weather/?size=230&fsize=12&bg=images/bg.png&repeat=repeat-x&r=1&w=1&g=1&col=1&d=0" width="240" height="450" scrolling="no"></iframe> 
    </div>    
</div><!-- left_panel -->